export const SET_NEXT_MONTH = 'SET_NEXT_MONTH';
export const SET_PREV_MONTH = 'SET_PREV_MONTH';

export const CREATE_REMINDER = 'CREATE_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
