export const SET_CURRENT_MONTH_RANGE = 'SET_CURRENT_MONTH_RANGE';
export const SET_NEXT_MONTH_RANGE = 'SET_NEXT_MONTH_RANGE';
export const SET_PREV_MONTH_RANGE = 'SET_PREV_MONTH_RANGE';

export const CREATE_REMINDER = 'CREATE_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
